### ISSUE TITLE
Build package for ubuntu 20.04 (focal) and upload it to ppa.

### ISSUE THREAD

**Issue by vskubriev** [dm0/nvidia-power-manager#7]
Build package for ubuntu 20.04 (focal) and upload it to ppa.

**Comment by dm0** [comment]
Technically the package is there and it installs in docker.

But I don't have live system with Ubuntu 20.04, so I can't check if it really works.

Please check and let me know if it work.

**Comment by dm0** [comment]
Assuming the package is working on 20.04. Closing the issue.
